cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED CMAKE_PREFIX_PATH AND DEFINED ENV{Qt6_DIR})
    set(CMAKE_PREFIX_PATH $ENV{Qt6_DIR})
endif()

if(NOT DEFINED CMAKE_PREFIX_PATH AND DEFINED ENV{QTDIR})
    set(CMAKE_PREFIX_PATH $ENV{QTDIR})
endif()

message(STATUS "CMAKE_PREFIX_PATH = ${CMAKE_PREFIX_PATH}")
